### ISSUE TITLE
language-markdown support needs to be fixed

### ISSUE THREAD

**Issue by plttn** [plttn/pubster-syntax#3]
See burodepeper/language-markdown#83.

Should eventually be fixed.

**Comment by plttn** [comment]
Will be resolved as of v1.0.0.

**Comment by burodepeper** [comment]
I've looked at your code, and as far as I can see (without installing it in dev-mode) the current version on your `master` branch looks good to go. I'd say that you `apm publish` it. The `less` is scoped to the generic `.markup` class (and therefore does not rely on the base scope of `language-markdown` or `language-gfm` for that matter, so I suppose you are good to go.

When I update `language-markdown` to `v1.0.0` I reckon you'd only gain more things that are highlighted than less. Let me know (in this issue) if you run into any other issues, and I'll be happy to take a look at them.

Also, in https://github.com/plttn/tubster-syntax/blob/master/styles/base.less, I suggest (in the spirit of the cascading philosophy of css) you move the `import`s (except for `colors.less`) to the end of the document, or at least move them after the declarations for the generic scopes. And if I can be a complete nitpicker: please nest your declarations for some extra clarity.

**Comment by plttn** [comment]
@burodepeper, Thanks for the heads up on import locations and nesting. I've gone ahead and done those on master, but `language-markdown` support in the `apm` version will have to wait until I can get my `apm rename` issue resolved.

Thanks for giving it a look!
